import type { ConnectedApp, Platform } from "@/types"

// DEV/UI debug fixtures for Home surfaces only.
// Not production data; safe to change/remove as UI scenarios evolve.
export const testPlatforms: Platform[] = [
  {
    id: "chatgpt",
    company: "OpenAI",
    name: "ChatGPT",
    filename: "chatgpt",
    description: "OpenAI data export",
    isUpdated: false,
    logoURL: "",
    needsConnection: true,
    connectURL: "https://chatgpt.com/",
    connectSelector: "nav a[href^='/c/']",
    exportFrequency: null,
    vectorize_config: { documents: "content" },
    runtime: "playwright",
  },
  {
    id: "linkedin",
    company: "LinkedIn",
    name: "LinkedIn",
    filename: "linkedin",
    description: "LinkedIn data export",
    isUpdated: false,
    logoURL: "",
    needsConnection: true,
    connectURL: null,
    connectSelector: null,
    exportFrequency: null,
    vectorize_config: null,
    runtime: null,
  },
  {
    id: "github",
    company: "GitHub",
    name: "GitHub",
    filename: "github",
    description: "GitHub data export",
    isUpdated: false,
    logoURL: "",
    needsConnection: true,
    connectURL: null,
    connectSelector: null,
    exportFrequency: null,
    vectorize_config: null,
    runtime: null,
  },
  {
    id: "shop",
    company: "Shop",
    name: "Shop",
    filename: "shop",
    description: "Shop data export",
    isUpdated: false,
    logoURL: "",
    needsConnection: true,
    connectURL: null,
    connectSelector: null,
    exportFrequency: null,
    vectorize_config: null,
    runtime: null,
  },
  {
    id: "spotify",
    company: "Spotify",
    name: "Spotify",
    filename: "spotify",
    description: "Spotify data export",
    isUpdated: false,
    logoURL: "",
    needsConnection: true,
    connectURL: null,
    connectSelector: null,
    exportFrequency: null,
    vectorize_config: null,
    runtime: null,
  },
  {
    id: "instagram",
    company: "Meta",
    name: "Instagram",
    filename: "instagram",
    description: "Instagram data export",
    isUpdated: false,
    logoURL: "",
    needsConnection: true,
    connectURL: null,
    connectSelector: null,
    exportFrequency: null,
    vectorize_config: null,
    runtime: null,
  },
]

export const testConnectedPlatforms: Platform[] = testPlatforms

// DEV/UI debug sample for Connected Apps.
export const testConnectedApps: ConnectedApp[] = [
  {
    id: "rickroll",
    name: "RickRoll",
    icon: "R",
    permissions: ["Data exports"],
    connectedAt: "2026-01-16T12:00:00.000Z",
  },
]
