[program:api-server]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/node /app/cloud-server/dist/server.js
autorestart=true
priority=900
user=%(ENV_USER)s
stdout_logfile=/var/log/neko/api-server.log
stdout_logfile_maxbytes=100MB
redirect_stderr=true
