import type { MockApp } from "./types"

export const mockApps: MockApp[] = [
  {
    id: "rickroll",
    name: "RickRoll Facts",
    description: "Discover fun facts from your ChatGPT conversations",
    icon: "R",
    category: "Demo",
    externalUrl: "https://rickroll.vana.com",
    status: "live",
    dataRequired: ["ChatGPT"],
  },
  {
    id: "vana-trainer",
    name: "Vana Trainer",
    description: "Train AI models on your personal data",
    icon: "🤖",
    category: "AI Training",
    status: "coming-soon",
    dataRequired: ["ChatGPT", "Reddit", "Twitter"],
  },
  {
    id: "data-broker",
    name: "Data Marketplace",
    description: "Sell access to your data securely",
    icon: "💎",
    category: "Marketplace",
    status: "coming-soon",
    dataRequired: ["Any"],
  },
  {
    id: "personal-assistant",
    name: "Personal AI Assistant",
    description: "Get personalized insights from your data",
    icon: "🧠",
    category: "Productivity",
    status: "coming-soon",
    dataRequired: ["Gmail", "Calendar", "Notion"],
  },
  {
    id: "social-analyzer",
    name: "Social Insights",
    description: "Analyze your social media presence",
    icon: "📊",
    category: "Analytics",
    status: "coming-soon",
    dataRequired: ["Twitter", "LinkedIn", "Reddit"],
  },
  {
    id: "health-tracker",
    name: "Health Data Sync",
    description: "Aggregate and analyze health metrics",
    icon: "❤️",
    category: "Health",
    status: "coming-soon",
    dataRequired: ["Fitbit", "Apple Health"],
  },
  {
    id: "content-creator",
    name: "Content Vault",
    description: "Organize and monetize your content",
    icon: "📁",
    category: "Media",
    status: "coming-soon",
    dataRequired: ["YouTube", "Instagram", "TikTok"],
  },
]
