// ============================================================================
// DO NOT EDIT — generated by scripts/generate-platform-registry.js
// Source: connectors/registry.json + src/lib/platform/registry.overlay.json
// ============================================================================

import type { PlatformRegistryEntry } from "./registry";

export const PLATFORM_REGISTRY_GENERATED: PlatformRegistryEntry[] = [
  {
    id: "chatgpt",
    displayName: "ChatGPT",
    brandDomain: "chatgpt.com",
    iconKey: "chatgpt",
    platformIds: ["chatgpt-playwright", "chatgpt"],
    aliases: ["openai"],
    availability: "requiresConnector",
    showInConnectList: true,
    ingestScope: "chatgpt.conversations"
  },
  {
    id: "github",
    displayName: "GitHub",
    brandDomain: "github.com",
    iconKey: "github",
    platformIds: ["github-playwright", "github"],
    availability: "requiresConnector",
    showInConnectList: true,
    ingestScope: "github.profile"
  },
  {
    id: "instagram-ads",
    displayName: "Instagram Ads",
    brandDomain: "instagram.com",
    iconKey: "instagram",
    platformIds: ["instagram-ads-playwright", "instagram-ads", "instagram"],
    availability: "requiresConnector",
    showInConnectList: false,
    ingestScope: "instagram.ads"
  },
  {
    id: "instagram",
    displayName: "Instagram",
    brandDomain: "instagram.com",
    iconKey: "instagram",
    platformIds: ["instagram-playwright", "instagram"],
    aliases: ["meta"],
    availability: "requiresConnector",
    showInConnectList: true,
    ingestScope: "instagram.posts"
  },
  {
    id: "linkedin",
    displayName: "LinkedIn",
    brandDomain: "linkedin.com",
    iconKey: "linkedin",
    platformIds: ["linkedin-playwright", "linkedin"],
    availability: "requiresConnector",
    showInConnectList: true,
    ingestScope: "linkedin.profile"
  },
  {
    id: "oura",
    displayName: "Oura Ring",
    brandDomain: "ouraring.com",
    iconKey: "oura",
    platformIds: ["oura-playwright", "oura"],
    aliases: ["ouraring"],
    availability: "requiresConnector",
    showInConnectList: true,
    ingestScope: "oura.readiness"
  },
  {
    id: "shop",
    displayName: "Shop",
    brandDomain: "shop.app",
    iconKey: "shop",
    platformIds: ["shop-playwright", "shop"],
    aliases: ["shopify"],
    availability: "requiresConnector",
    showInConnectList: true,
    ingestScope: "shop.orders"
  },
  {
    id: "spotify",
    displayName: "Spotify",
    brandDomain: "spotify.com",
    iconKey: "spotify",
    platformIds: ["spotify-playwright", "spotify"],
    availability: "requiresConnector",
    showInConnectList: true,
    ingestScope: "spotify.savedTracks"
  },
  {
    id: "youtube",
    displayName: "YouTube",
    brandDomain: "youtube.com",
    iconKey: "youtube",
    platformIds: ["youtube-playwright", "youtube"],
    availability: "requiresConnector",
    showInConnectList: true,
    ingestScope: "youtube.profile"
  }
];
